export const GET_USERS = 'GET_USERS';
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_REFRESH = 'GET_USERS_REFRESH'
export const SEARCH_USERS = 'SEARCH_USERS'
